"""
Nodes (in order):
  1. decode_vin     - calls NHTSA API via MCP-style function
  2. retrieve_tsbs  - queries FAISS vector store via RAG
  3. run_agents     - runs 4 CrewAI agents
  4. format_report  - assembles the final structured report

"""
import sys
import os
import requests
from typing import TypedDict, List, Optional
from langgraph.graph import StateGraph, END
from dotenv import load_dotenv
sys.path.insert (0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv()

NHTSA_VIN_URL = "https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVin/{vin}?format=json"


class DiagnosisState(TypedDict):
    vin:           str
    dtc_codes:     List[str]
    vehicle_info:  dict
    tsb_docs:      List[str]
    crew_result:   str
    final_report:  str
    error:         Optional[str]


def decode_vin_node(state: DiagnosisState) -> DiagnosisState:
    """
    Node 1: Decode the VIN using the NHTSA public API.
    Extracts make, model, year, engine.
    Falls back to empty dict on network error.
    """
    vin = state["vin"]
    fields = {
        "Make":                  "make",
        "Model":                 "model",
        "Model Year":            "year",
        "Engine Configuration":  "engine",
        "Fuel Type - Primary":   "fuel_type",
    }
    try:
        response = requests.get(NHTSA_VIN_URL.format(vin=vin), timeout=10)
        results  = response.json().get("Results", [])
        vehicle  = {"vin": vin}
        for item in results:
            key = fields.get(item["Variable"])
            if key and item.get("Value") and item["Value"] != "Not Applicable":
                vehicle[key] = item["Value"]
        print(f"  VIN decoded: {vehicle.get('make','')} {vehicle.get('model','')} {vehicle.get('year','')}")
        return {**state, "vehicle_info": vehicle}
    except Exception as exc:
        print(f"  VIN decode failed: {exc} — using fallback")
        return {**state, "vehicle_info": {"vin": vin}, "error": str(exc)}


def retrieve_tsbs_node(state: DiagnosisState) -> DiagnosisState:
    """
    Node 2: Query the FAISS vector store via RAG retriever.
    Builds a natural language query from vehicle + DTC codes,
    retrieves the top 5 relevant TSB/recall chunks.
    """
    from src.rag import load_retriever

    vehicle = state["vehicle_info"]
    query = (
        f"{vehicle.get('make','')} {vehicle.get('model','')} "
        f"{vehicle.get('year','')} DTC: {' '.join(state['dtc_codes'])}"
    )
    retriever = load_retriever()
    docs = retriever.invoke(query)
    tsb_texts = [doc.page_content for doc in docs]
    print(f"  Retrieved {len(tsb_texts)} TSB/recall chunks")
    return {**state, "tsb_docs": tsb_texts}


def run_agents_node(state: DiagnosisState) -> DiagnosisState:
    """
    Node 3: Run the CrewAI multi-agent diagnosis crew.
    Passes vehicle info, DTC codes, and retrieved TSB context
    to the 4-agent crew. Returns the final crew output.
    """
    from src.agents import run_diagnosis_crew

    tsb_context = "\n\n---\n\n".join(state["tsb_docs"][:3])
    print("  Running CrewAI agents ...")
    result = run_diagnosis_crew(
        vehicle_info=state["vehicle_info"],
        dtc_codes=state["dtc_codes"],
        tsb_context=tsb_context,
    )
    return {**state, "crew_result": result}


def format_report_node(state: DiagnosisState) -> DiagnosisState:
    """
    Node 4: Assemble the final structured report.
    Combines vehicle info, DTC codes, and crew analysis
    into a formatted text report.
    """
    vehicle = state["vehicle_info"]
    report = (
        "=" * 50 + "\n"
        "AUTODIAG AI — DIAGNOSTIC REPORT\n"
        + "=" * 50 + "\n\n"
        f"Vehicle : {vehicle.get('make','')} {vehicle.get('model','')} ({vehicle.get('year','')})\n"
        f"VIN     : {vehicle.get('vin','N/A')}\n"
        f"DTC     : {', '.join(state['dtc_codes'])}\n"
        f"Sources : {len(state.get('tsb_docs', []))} TSB documents retrieved\n\n"
        "DIAGNOSIS:\n"
        + "-" * 30 + "\n"
        + state.get("crew_result", "No diagnosis available.")
        + "\n\n"
        "Generated by AutoDiag AI — for professional use only.\n"
    )
    print("  Report formatted.")
    return {**state, "final_report": report}


def build_graph():
    """Build and compile the LangGraph state machine."""
    workflow = StateGraph(DiagnosisState)

    workflow.add_node("decode_vin",    decode_vin_node)
    workflow.add_node("retrieve_tsbs", retrieve_tsbs_node)
    workflow.add_node("run_agents",    run_agents_node)
    workflow.add_node("format_report", format_report_node)

    workflow.set_entry_point("decode_vin")
    workflow.add_edge("decode_vin",    "retrieve_tsbs")
    workflow.add_edge("retrieve_tsbs", "run_agents")
    workflow.add_edge("run_agents",    "format_report")
    workflow.add_edge("format_report", END)

    return workflow.compile()


if __name__ == "__main__":
    graph = build_graph()
    print("Running LangGraph diagnosis pipeline ...\n")

    initial_state = {
        "vin":          "WBA8E9G50HNU60241",
        "dtc_codes":    ["P0301"],
        "vehicle_info": {},
        "tsb_docs":     [],
        "crew_result":  "",
        "final_report": "",
        "error":        None,
    }

    result = graph.invoke(initial_state)
    print("\n" + result["final_report"])
